version: '3.8'

services:
 #orderdb: sqlserver
 orderdb:
  container_name: orderdb
  environment: 
   SA_PASSWORD: "Passw0rd!"
   ACCEPT_EULA: "Y"
  restart: always
  volumes:
   - sqlserver_data:/var/lib/sqlserver/data
  ports:
   - "1435:1433"

 #productdb: mysql
 productdb:
  container_name: productdb
  environment: 
   MYSQL_ROOT_PASSWORD: "Passw0rd!"
  restart: always
  volumes:
   - mysql_data:/var/lib/mysql
  ports:
   - "3306:3306"

 #customerdb: postgres
 customerdb:
  container_name: customerdb
  environment: 
   - POSTGRES_USER=admin
   - POSTGRES_PASSWORD=Passw0rd!
   - POSTGRES_DB=DiscountDb
  restart: always
  volumes:
   - postgres_data:/var/lib/postgresql/data
  ports:
   - "5433:5432"

 #basketdb: redis
 basketdb:
  container_name: basketdb
  restart: always
  ports:
   - "6379:6379"

 #inventorydb: mongo
 inventorydb:
  container_name: inventorydb
  restart: always
  volumes:
   - mongo_data:/data/db
  ports:
   - "27017:27017"

 #infrastructure section
 rabbitmq:
  container_name: rabbitmq
  restart: always
  ports:
   - "5672:5672"
   - "15672:15672"

 pgadmin:
  container_name: pgadmin
  environment:
   - PGADMIN_DEFAULT_EMAIL=admin@tedu_microservice.com
   - PGADMIN_DEFAULT_PASSWORD=admin1234
  restart: always
  ports:
   - "5050:80"
  volumes:
   - pgadmin_data:/root/.pgadmin

 portainer:
  container_name: portainer
  restart: always
  ports:
   - "8080:8000"
   - "9000:9000"
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - portainer_data:/data

 elasticsearch:
  container_name: elasticsearch
  environment:
   - xpack.monitoring.enabled=true
   - xpack.watcher.enabled=false
   - "ES_JAVA_OPTS=-Xms512m -Xmx512"
   - discovery.type=single-node
  ports:
   - "9200:9200"
  volumes:
   - elasticsearch_data:/usr/share/elasticsearch/data

 kibana:
  container_name: kibana
  environment:
   - ELASTICSEARCH_URL=http://elasticsearch:9200
  depends_on:
   - elasticsearch
  ports:
   - "5601:5601"